### PR TITLE
Add addon installation support

### PR DESCRIPTION
**Pull request by Joel-Paul**
Allows user to select addons to install along with the base mod.

### CODE REVIEW

**Comment by GencoreOperative** [comment]
Thank you very much for this Pull Request! I am honestly surprised to have any contributors for this little project.

Which mods do you run in the game? I've not tried any yet. Which would you recommend? The forums are currently down so I cannot currently download any.

As for the change in this pull request I'm interested to know your thoughts here and have a few questions to consider:

*UI Layout*
For the users workflow I had currently assumed that the most important thing they would be doing is selecting the patch location. This is why the patch selection panel is placed at the top of the UI. For this change you have moved the panel below the Minecraft home selection. Is that to bring the association between the patch and the Addons closer together?

*Addon Order*
Another question I had was around the ordering of addons when building the patched Jar. Does the order matter for addons? Do they make unique changes or are they infact overlapping and have dependencies between addons?

*Patching and Upgrading*
Another question I was considering was around users who patch with addons and then at a later point in time update but forget or do not apply the same addons. Would this result in problems with that players save games? Whilst I am not suggesting we should aim to fix all eventualities however it might be good to warn the user that they are patching an install that previously had addons installed. It might be good to track the addons patched in the version file.

For these questions, if there are any code changes coming out of them, would you like to make those changes or would you like me to take on those? This is the first open source project pull request I've worked with so I'm not entirely sure on the best approach or indeed what you would prefer?

**Comment by Joel-Paul** [comment]
> "Which mods do you run in the game?"

The main mods I use are the Skin Fix mod (since the server older versions of Minecraft get their skins from is outdated) and the CraftGuide mod (to see recipes in-game).

> _UI Layout_

Basically what you said, to bring the association between patches and addons together. Of course, if you believe another layout is better I'm all for it, it was just personal preference.

> _Addon Order_

I'm actually not 100% sure if order matters. I suspect it might not, especially with the little amount of addons present for BTW, I just added it in case. I'll admit the way I implemented the ordering isn't very clean though.

> _Patching and Upgrading_

For client side addons this shouldn't be an issue, and I know for some addons that add blocks, the blocks will simply disappear from the world when not installed, though I can't say for certain that for all addons there won't be a problem. Nonetheless I do agree that it's a good idea to warn the user.

> "For these questions [...]"

I'm not sure if it comes across from the code, but I am not very experienced in Java at all, and this was the first time I've ever had to work with Observers, so figuring that out took a while :P. This is basically also my first pull request I've done, so I'm not sure what the best approach is either, however I am more than willing to apply any changes you want to the code.

**Comment by GencoreOperative** [comment]
Now the BTW forums are back online I've taken time to look through a number of mods and try out your changes. They work very well so thank again for putting this together!

Also I've been thinking about how best to collaborate on this change. I was going to propose the following changes with rationale for them:

* Switch the position of the "Minecraft Home" section to below the "Better Than Wolves Addons": This achieves the objective of placting the most important parts (Patch & Addons) at the top of the UI.

* Remove the Move Up/Move Down buttons: From what I have learned so far there is no dependencies between the mods. Simplifying the UI to just the things the user needs will make it more approachable for new users.

* Remove the folder selection functionality once a zip is selected. At the moment I cannot find any mod that needs this feature. Simplification will help the user here again. Less decisions is better for users who might be new to the game.

The goal of this installer is to make it as easy to install the mod as possible so that there is a chance that new players can join this great mod.

If these changes sound ok to you then I would be happy to work with you on them.

**Comment by Joel-Paul** [comment]
Thanks for getting back, and I'm happy to make most of these changes. However both the Deco Addon and the Jorge's Miscellaneous Addon have separate client and server files, which is why I had to add the folder selector for the zip. Unless there's a way to determine if the given directory is for the client, I don't know how else to solve this problem.

Apart from that, I'll get started on the rest of the changes as soon as I'm free.

**Comment by Joel-Paul** [comment]
So I've gone ahead and added a bit of code that minimises the need for the user to use the zip folder selection. It basically searches the zip for any .class files in the root folder, and if it finds any it assumes the folder to be extracted is the root folder. I also check if there are any folders the Deco Addon and Jorge's Miscellaneous Addon use for their client files, and if found, extracts from these files.

I don't imagine there will be many other edge cases given the lack of addons being developed, so this will probably be enough for now.

**Comment by GencoreOperative** [comment]
Amazing work and good decisions there. I'll give the changes a test and then merge this into the code base.

**Comment by GencoreOperative** [comment]
Ok, all looks good. Thank you again for this. I'll merge this in now and work on adding some credits so your name can appear there.

**Pull request merged**
